export enum TicketType {
    HR = "HR",
    IT = "IT",
}

export enum HrType {
    LEAVE_BALANCE = "LEAVE_BALANCE",
    LEAVE_POLICY = "LEAVE_POLICY",
    PAYROLL = "PAYROLL",
    PF = "PF",
    KEKA_ISSUES = "KEKA_ISSUES",
    SODEXO_FOOD_COUPONS = "SODEXO_FOOD_COUPONS",
    HEALTH_INSURANCE = "HEALTH_INSURANCE",
    ANY_FORM_OF_LETTER = "ANY_FORM_OF_LETTER",
    REFERRAL_APPLICATION = "REFERRAL_APPLICATION",
    COURSE_PURCHASE = "COURSE_PURCHASE",
    BANK_ACCOUNT_ISSUE = "BANK_ACCOUNT_ISSUE",
}

export enum ItType {
    LAPTOP_BOOTUP = "LAPTOP_BOOTUP",
    LAPTOP_CHARGER_NOT_WORKING = "LAPTOP_CHARGER_NOT_WORKING",
    LAPTOP_BATTERY_LIFE = "LAPTOP_BATTERY_LIFE",
    ADD_RAM = "ADD_RAM",
    NEW_MONITOR = "NEW_MONITOR",
    NEW_KEYBOARD = "NEW_KEYBOARD",
    NEW_MOUSE = "NEW_MOUSE",
    MOBILE_PHONE_ISSUE = "MOBILE_PHONE_ISSUE",
    MOBILE_DATA_CABLE_ISSUE = "MOBILE_DATA_CABLE_ISSUE",
    HARD_DISK_FAILURE = "HARD_DISK_FAILURE",
}

export const ticketTypes = Object.values(TicketType);
export const hrTypes = Object.values(HrType);
export const itTypes = Object.values(ItType);
